### ISSUE TITLE
Thanks and Left/Right Arrows

### ISSUE THREAD

**Issue by klihelp** [enyo/vocal-coach#1]
Thanks for simple and wonderful vocal couch website! You are a great multi talent!

Left/right arrows could navigate between excersizes?

**Comment by enyo** [comment]
Hey! Thanks :) I wasn't anticipating anybody looking at this or trying it out. Nice to see that somebody is using it.

Good ideas! I'll implement them soon.

**Comment by enyo** [comment]
Now tracked by https://gitlab.com/meno/vocal-coach/issues/3
