### ISSUE TITLE
Local cache the user/custom excersizes

### ISSUE THREAD

**Issue by klihelp** [enyo/vocal-coach#2]
An idea would be to local cache the user made / custom excersizes and show them on revisit..

**Comment by enyo** [comment]
The new project at gitlub, and [deployed here](http://meno.gitlab.io/vocal-coach/#/exercise/gamme) saves exercises automatically now, and provides a link that you can bookmark for exercises.

**Comment by klihelp** [comment]
great work!:)
Missing something from the old project..

**Comment by enyo** [comment]
What do you mean "missing something"?

**Comment by klihelp** [comment]
The catchy visual design of presenting the notes / exercises. The old project was started  60% of that, then opened up the control section.

![screen shot 2017-02-10 at 01 29 53](https://cloud.githubusercontent.com/assets/3436611/22809152/91054f30-ef30-11e6-93b6-f67a4d03e3d7.png)

**Comment by enyo** [comment]
Oh yes notes are coming back soon :)

**Comment by enyo** [comment]
New version now has the notes again
